title: "Shaan Patel"
description: "Personal Website"
markdown: kramdown

# Navbar
nav:
  - name: "Home"
    link: /
  - name: "About"
    link: /about
  - name: "CV"
    link: /cv
  - name: "Projects"
    link: /projects
  - name: "Publications"
    link: /publications
  - name: "News"
    link: /news
  - name: "Contact"
    link: /contact
