title: "Shaan D. Patel"
description: "Astrophysics Researcher"
baseurl: "" # leave empty for user.github.io repo
url: "shaandpatel.github.io"     # your GitHub Pages URL
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: true

# Navbar items
nav:
  - name: "Home"
    link: /
  - name: "About"
    link: /about
  - name: "CV"
    link: /cv
  - name: "Projects"
    link: /projects
  - name: "Publications"
    link: /publications
  - name: "News"
    link: /news
  - name: "Contact"
    link: /contact
